### ISSUE TITLE
Unable to control devices over BLE - Failed to perform the action light/turn_on. 'NoneType' object has no attribute 'write_gatt_char'

### ISSUE THREAD

**Issue by padgriffin** [Beshelmek/govee_ble_lights#59]
## Version of the integration
0.1.1

## Device setup

H617C, H618A

## Describe the bug

Device cannot be controlled via integration, outputs "AttributeError: 'NoneType' object has no attribute 'write_gatt_char'". Device is detected by HA and able to be added, but errors when a command is given.

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/govee-ble-lights/light.py", line 277, in async_turn_on
    await client.write_gatt_char(UUID_CONTROL_CHARACTERISTIC, command, False)
          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write_gatt_char'

```

**Comment by padgriffin** [comment]
Rombond's H617A BLE fork seems to have fixed this and reliably controls the H617C.

https://github.com/Rombond/h617a_govee_ble_lights

**Comment by fabian19vs** [comment]
Having the exact same log error for my H6010 light bulb
